In [ ]:
# dataset from: http://www.bakardjian.com/work/ssvep_data_Bakardjian.html

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import mne, glob
from scipy.io import loadmat

In [11]:
location = "C:/Users/alexc/OneDrive/Documents/Taiwan Classes/Second Semester/Brain Computer Interfaces/Week 13/BCI-HW6/Matlab Procedure/Dataset/Resulting mat files/"

files8Hz = glob.glob(location+"8Hz.mat")
files14Hz = glob.glob(location+"14Hz.mat")
files28Hz = glob.glob(location+"28Hz.mat")

freq8 = loadmat(files8Hz[0])
freq14 = loadmat(files14Hz[0])
freq28 = loadmat(files28Hz[0])

In [46]:

index = []
for i in range(1,61):
    index.append("Trial #" + str(i))

freq8_df = pd.DataFrame(freq8['FFTpower'], index = index)
freq14_df = pd.DataFrame(freq14['FFTpower'], index = index)
freq28_df = pd.DataFrame(freq28['FFTpower'], index = index)

In [129]:
freq8_df["Target_Hz"] = "8"
freq14_df["Target_Hz"] = "14"
freq28_df["Target_Hz"] = "28"

freq8_df.head()
#freq14_df.head()
#freq28_df.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,Channel,Target_Hz
Trial #1,45.451625,45.044891,42.934973,41.322231,41.391377,41.119485,40.354551,40.042102,39.396210,38.244057,...,27.282433,27.308212,26.583426,26.369623,26.506874,27.107757,28.018314,27.430429,O1,8
Trial #2,45.511883,44.413034,41.478950,37.777977,37.957134,38.163092,37.507486,37.856673,37.672448,37.139928,...,26.218676,25.588342,24.508643,23.351366,24.087403,24.789970,24.950139,25.906049,O1,8
Trial #3,42.278902,42.007243,40.886586,39.273608,37.423654,36.936417,37.206827,36.939698,36.485052,35.818029,...,26.537004,26.270066,26.703577,26.790589,26.181994,26.558552,26.807987,26.904903,O1,8
Trial #4,45.833185,44.443683,41.710629,41.262282,41.258446,40.456957,39.969211,38.562069,37.472087,37.566324,...,26.394300,27.016919,28.252467,29.488319,29.344418,28.966022,28.603251,27.436188,O1,8
Trial #5,44.502296,43.632440,42.115278,41.085873,40.268827,40.240690,39.416283,38.997042,38.552509,38.411532,...,26.136726,26.162718,25.956349,27.121652,27.302775,27.029681,27.335215,28.019882,O1,8

In [147]:
frequencies_df = [freq8_df,freq14_df, freq28_df]

for freq in frequencies_df:
    freq["Channel"] = np.NaN

    freq.Channel.loc[0:20] = "O1"
    freq.Channel.loc[20:40] = "OZ"
    freq.Channel.loc[40:60] = "O2"

freq8_df.head()

c:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3437: FutureWarning: Slicing a positional slice with .loc is not supported, and will raise TypeError in a future version.  Use .loc with labels or .iloc with positions instead.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,Channel,Target_Hz
Trial #1,45.451625,45.044891,42.934973,41.322231,41.391377,41.119485,40.354551,40.042102,39.396210,38.244057,...,27.282433,27.308212,26.583426,26.369623,26.506874,27.107757,28.018314,27.430429,O1,8
Trial #2,45.511883,44.413034,41.478950,37.777977,37.957134,38.163092,37.507486,37.856673,37.672448,37.139928,...,26.218676,25.588342,24.508643,23.351366,24.087403,24.789970,24.950139,25.906049,O1,8
Trial #3,42.278902,42.007243,40.886586,39.273608,37.423654,36.936417,37.206827,36.939698,36.485052,35.818029,...,26.537004,26.270066,26.703577,26.790589,26.181994,26.558552,26.807987,26.904903,O1,8
Trial #4,45.833185,44.443683,41.710629,41.262282,41.258446,40.456957,39.969211,38.562069,37.472087,37.566324,...,26.394300,27.016919,28.252467,29.488319,29.344418,28.966022,28.603251,27.436188,O1,8
Trial #5,44.502296,43.632440,42.115278,41.085873,40.268827,40.240690,39.416283,38.997042,38.552509,38.411532,...,26.136726,26.162718,25.956349,27.121652,27.302775,27.029681,27.335215,28.019882,O1,8

In [148]:
all_freq_df = pd.concat([freq8_df,freq14_df],join="inner")
all_freq_df = pd.concat([all_freq_df,freq28_df],join="inner")

In [150]:
#To rename the index to have 180, and not 3 sets of (1 to 60)
new_index = []
for i in range(1,181):
    new_index.append("Trial #" + str(i))

all_freq_df = all_freq_df.reset_index(drop = True, inplace=False)
all_freq_df = np.array(all_freq_df)
all_freq_df = pd.DataFrame(all_freq_df, index = new_index)
all_freq_df.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
Trial #1,45.451625,45.044891,42.934973,41.322231,41.391377,41.119485,40.354551,40.042102,39.39621,38.244057,...,27.282433,27.308212,26.583426,26.369623,26.506874,27.107757,28.018314,27.430429,O1,8
Trial #2,45.511883,44.413034,41.47895,37.777977,37.957134,38.163092,37.507486,37.856673,37.672448,37.139928,...,26.218676,25.588342,24.508643,23.351366,24.087403,24.78997,24.950139,25.906049,O1,8
Trial #3,42.278902,42.007243,40.886586,39.273608,37.423654,36.936417,37.206827,36.939698,36.485052,35.818029,...,26.537004,26.270066,26.703577,26.790589,26.181994,26.558552,26.807987,26.904903,O1,8
Trial #4,45.833185,44.443683,41.710629,41.262282,41.258446,40.456957,39.969211,38.562069,37.472087,37.566324,...,26.3943,27.016919,28.252467,29.488319,29.344418,28.966022,28.603251,27.436188,O1,8
Trial #5,44.502296,43.63244,42.115278,41.085873,40.268827,40.24069,39.416283,38.997042,38.552509,38.411532,...,26.136726,26.162718,25.956349,27.121652,27.302775,27.029681,27.335215,28.019882,O1,8

In [151]:
from sklearn.utils import shuffle
all_freq_df = shuffle(all_freq_df)
all_freq_df

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
Trial #129,36.705623,36.414217,35.224911,33.758235,31.183611,30.723135,29.891786,29.007527,27.974278,27.0787,...,21.722163,22.910241,23.326217,22.391413,21.499927,21.086272,21.853259,22.107729,O1,28
Trial #106,36.384946,36.234431,35.985635,34.573839,33.787545,32.821838,31.371758,30.335242,30.300008,29.577906,...,22.31948,22.719332,22.456522,23.031407,22.814384,21.889186,22.387943,23.396755,O2,14
Trial #140,55.456611,54.56803,52.049358,50.153409,49.389249,49.014391,47.891096,46.042425,45.709082,45.958063,...,36.354199,36.873952,37.228892,36.804262,35.836657,36.060596,35.682514,34.653353,O1,28
Trial #154,54.05765,52.867113,50.255749,47.786172,47.035813,46.016682,45.563431,44.088322,42.975035,42.013486,...,34.49864,34.079657,33.743938,34.829433,35.147205,35.387897,34.682387,33.941184,OZ,28
Trial #14,60.384718,59.052627,56.240594,54.623468,53.780034,53.275336,52.70108,51.585518,50.915357,49.818009,...,43.056479,42.51795,43.05459,43.169115,43.994765,43.623825,43.228678,43.605499,O1,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Trial #9,33.799631,33.884979,32.7861,31.860027,31.316007,30.422632,28.319537,28.12746,28.546718,27.693908,...,20.430384,20.475743,20.869482,21.361346,20.700703,20.703127,19.754883,19.579379,O1,8
Trial #10,32.408827,32.613937,31.417873,31.161243,30.040653,28.857739,28.815608,28.21514,27.946747,27.376659,...,20.902489,19.74033,18.87325,18.266395,19.252466,19.214153,19.276672,18.876923,O1,8
Trial #79,53.853267,52.557442,50.705794,49.888179,48.936619,46.849375,44.930557,43.68669,43.286088,43.316216,...,34.291859,34.033135,34.067182,34.634831,34.198419,33.059602,32.610989,33.145133,O1,14
Trial #26,31.275117,31.012683,29.439303,28.085801,26.553461,25.831279,25.333779,24.80514,25.400532,24.591213,...,16.99523,16.957717,17.731889,17.95247,18.356145,18.141823,18.021124,16.98931,OZ,8
Trial #169,38.882123,39.152708,38.302881,37.131635,36.611103,35.416815,34.023354,33.597684,32.485724,31.149762,...,23.47112,23.41615,23.712969,23.638594,22.998445,22.117907,21.923948,21.693772,O2,28

In [152]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

x = all_freq_df.iloc[:,0:59]
y = all_freq_df.iloc[:,60:61]

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.05,random_state=42)

In [153]:
#Import svm model
from sklearn import svm


rbf = svm.SVC(kernel='rbf', gamma=0.5, C=0.1)

rbf.fit(X_train, y_train)

y_pred = rbf.predict(X_test)

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

In [154]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.2222222222222222